---

- name: Deleting all apps
  command: >
    pm2 delete all
  register: command_result
  failed_when: "'[ERROR]' in command_result.stderr"

- debug: var=pwd

- name: Starting apps
  environment: "{{ item.env | default({}) }}"
  command: "pm2 start {{ item.run }} {{ item.args | default('') }}"
  args:
    chdir: "{{ item.path | default(omit) }}"
  with_items: pm2_apps
